### ISSUE TITLE
Upgrade pexpect to avoid "'asyncio' has no attribute 'coroutine'" error

### ISSUE THREAD

**Issue by andornaut** [gabe565/pyruckus#21]
Pyruckus produces an error when executed on Python 3.11.3: 
```
AttributeError: module 'asyncio' has no attribute 'coroutine
````

#### Context:

* Home Assistant v2023.6.0 Docker image was recently published, which uses Python 3.11.3
* The previous release worked, but the current release produces an error on startup

Log:
```
2023-06-07 22:58:16.021 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Ruckus WIFI Access Point for ruckus_unleashed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/ruckus_unleashed/__init__.py", line 31, in async_setup_entry
    ruckus = await Ruckus.create(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyruckus/__init__.py", line 44, in create
    await ruckus.connect()
  File "/usr/local/lib/python3.11/site-packages/pyruckus/__init__.py", line 50, in connect
    result = await ssh.login(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyruckus/RuckusSSH.py", line 48, in login
    i = await self.expect(login_regex_array, timeout=login_timeout, async_=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pexpect/spawnbase.py", line 340, in expect
    return self.expect_list(compiled_pattern_list,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pexpect/spawnbase.py", line 366, in expect_list
    from ._async import expect_async
  File "/usr/local/lib/python3.11/site-packages/pexpect/_async.py", line 6, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'
```

I believe that this is caused by the pexpect library, [which contains](https://github.com/pexpect/pexpect/blob/e4732bd0f76936ac26884dada3f83046b2d6e72a/pexpect/_async.py#L7):

```
@asyncio.coroutine
def expect_async(expecter, timeout=None):
```
This [may be fixed](https://github.com/pexpect/pexpect/pull/732) in the (unreleased) [current master revision](https://github.com/pexpect/pexpect/blob/master/pexpect/_async.py), but perhaps not. [This issue](https://github.com/pexpect/pexpect/pull/715) appears to be related.

**Comment by andornaut** [comment]
[This issue appears to be fixed](https://github.com/home-assistant/core/issues/94264#issuecomment-1589532437) in the current "master" branch of pexpect.

Please consider installing pexpect from [this revision](https://github.com/pexpect/pexpect/commit/2532721644781543ca660e52d48a35bd93872fc1) - https://github.com/pexpect/pexpect/archive/2532721.zip - until a fixed version is released.

You can do so by updating requirements.txt to include:
```
pexpect @ https://github.com/pexpect/pexpect/archive/2532721.zip
```

**Comment by gabe565** [comment]
I have deprecated this repository since [aioruckus](https://github.com/ms264556/aioruckus) connects to Ruckus Unleashed devices without requiring SSH or Pexpect. The Home Assistant Ruckus integration will be stable once https://github.com/home-assistant/core/pull/94835 is merged!
